### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by deanpcmad** [kenn/dumper#11]
Hi there, I've recently found Dumper and it looks like a great idea.
I was wondering if you were thinking about making the main application open source as I'd prefer to host it myself as I'm storing confidential data in my databases and would prefer it not to be sent to a third party.
Thanks

**Comment by kenn** [comment]
Dumper is built around the idea that it should Just Work®. Just because it's open source doesn't mean you can run it without trouble. Also, your definition of third party is confusing to me - AWS S3 is a third party in my book. 😉

**Comment by deanpcmad** [comment]
I would probably be storing the backups locally and not sending them to S3. I'd also like to be able to encrypt the backups too
