### ISSUE TITLE
Slots

### ISSUE THREAD

**Issue by TJM** [kenn/dumper#8]
I know this is not strictly the right place to ask this question, but I looked around and couldn't find another better option. Please feel free to dump this and tell me the correct place to file this feature request.

Why does dumper.io limit us to 4 slots? It seems rather arbitrary, and the more slots available would just be more storage, which would be more money, right? Let's say, hypothetically, we have a contractual obligation to keep 2 weeks worth of backups. You are already keeping the one from 2 weeks ago, but we need the ability to select a backup from any day in the last 14. Sometimes you don't realize something is wrong till *after* backups have run, especially when something bad happens over a holiday weekend. You may not want to go back to the week before.

**Comment by kenn** [comment]
Thanks for feedback, your point is well taken.
